# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'react_native_playground' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for react_native_playground
  pod 'BuddyBuildSDK'

  target 'react_native_playgroundTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
